name: "Docker Image Build and Push"

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  AZURE_REGISTRY: lappreg.azurecr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_REGISTRY }}
          username: ${{ secrets.AZURECR_USERNAME }}
          password: ${{ secrets.AZURECR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: | 
            ${{env.AZURE_REGISTRY}}:latest
            ${{env.AZURE_REGISTRY}}:v1
