name: Hello World workflow

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hello world
        run: echo "Hello World"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodby world
        run: echo "Goodbye World"
        shell: bash