name: Create a comment on new issues

on:
  issues:
    types:
      - opened

jobs: 
  comment-whit-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump GH context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'